Raise minimum tested compiler to 1.58
Required by target-triple crate.

    error: failed to parse manifest at `~/.cargo/registry/src/github.com-1ecc6299db9ec823/target-triple-0.1.1/Cargo.toml`

    Caused by:
      failed to parse the `edition` key

    Caused by:
      supported edition values are `2015` or `2018`, but `2021` is unknown