Raise required toolchain on macos to 1.54.0
    error: linking with `cc` failed: exit code: 1
      |
      = note: "cc" "-m64" "-L" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.0.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.1.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.10.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.11.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.12.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.13.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.14.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.15.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.2.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.3.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.4.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.5.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.6.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.7.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.8.rcgu.o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.build_script_build.b8gzaqjb-cgu.9.rcgu.o" "-o" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64" "/Users/runner/work/argv/argv/target/debug/build/argv-5faff47a71811b64/build_script_build-5faff47a71811b64.3oi6ilyx3xknes6z.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/runner/work/argv/argv/target/debug/deps" "-L" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-ec578e0d01ad5d6e.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-5412e5af11009a97.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-03db0718fbd4a443.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-8df90fdde44531fa.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-080b75c76cf389d3.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-954947c96c071ed1.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-9a1775bac6aabe20.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-71147793b4cdc412.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-9fc81eecc6136c9a.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-4b64712313317864.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-1bcd644d1289b2fb.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-16c65b3b16ee989d.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-7dd67903be10326a.rlib" "/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-b5923fb6eca9603a.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
      = note: ld: in /Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-5412e5af11009a97.rlib(rust.metadata.bin), archive member 'rust.metadata.bin' with length 25725 is not mach-o or llvm bitcode file '/Users/runner/.rustup/toolchains/1.39.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-5412e5af11009a97.rlib'
              clang: error: linker command failed with exit code 1 (use -v to see invocation)