Raise minimum rust version to 1.36
Required by the alloc dependency in once_cell.

    error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
       --> once_cell-1.8.0/src/lib.rs:328:1
        |
    328 | extern crate alloc;
        | ^^^^^^^^^^^^^^^^^^^